### ISSUE TITLE
[Hacktoberfest] Add more checklist tips to "HTMLElements" section

### ISSUE THREAD

**Issue by PatricNox** [fossbarrow/ultimate-seo-checklist#3]
Add more here: https://github.com/fossbarrow/seo-checklist/tree/main/HTMLElements

**Comment by rudyt7** [comment]
Hi I would like to work on this issue

**Comment by PatricNox** [comment]
@rudyt7  This is a repetive issue, meaning you can add as many PR's you want as long as you follow the hacktober guidelines!

**Comment by oyakhilomee** [comment]
I'll like to work on this, however, I'll like to know if the merge is automated?

**Comment by PatricNox** [comment]
@oyakhilomee  It's not automated, but I'm handling all notifications so it'll be merged eventually.

**Comment by oyakhilomee** [comment]
Ok thanks, i'll make some changes and PR.

**Comment by ThejasreeKilari** [comment]
Hi I like to contribute. Made a PR. Have added Alt tag to images section in Html.

**Comment by PatricNox** [comment]
@ThejasreeKilari  Thank you! Feel free to add more additions! :)

**Comment by yuktagautam** [comment]
Hi ,I would like to contribute on this issue!

**Comment by PatricNox** [comment]
@yuktagautam  This is a repetive issue, meaning you can add as many PR's you want as long as you follow the hacktober guidelines!

**Comment by iamheru** [comment]
I would like to contribute.
Is that okay?

**Comment by PatricNox** [comment]
@iamheru  Of course, as many times as you desire. Just remember to follow the hacktoberfest rules!

**Comment by lucianomenddes** [comment]
ALT attribute section added

**Comment by lucianomenddes** [comment]
My contribution. happy hacktoberfest for all

**Comment by lucianomenddes** [comment]
Hi @PatricNox , l added the section href.
