### ISSUE TITLE
[Hacktoberfest] Add more to "Robots.txt"

### ISSUE THREAD

**Issue by PatricNox** [fossbarrow/ultimate-seo-checklist#4]
Add more tips and tricks here: https://github.com/fossbarrow/seo-checklist/tree/main/Robots.txt

**Comment by Annysah** [comment]
Hi, I would love to work on this?

**Comment by PatricNox** [comment]
@Annysah  Sure thing! This is a repetive issue meaning multiplie additions are welcome.

**Comment by Annysah** [comment]
Alright Thanks!
