### ISSUE TITLE
Domain linked in repo does not exist.

### ISSUE THREAD

**Issue by ImMattDavison** [fossbarrow/ultimate-seo-checklist#43]
The domain name linked in the repo (fossbarrow.io) is not a registered domains and should be registered or removed to avoid confusion.

**Comment by PatricNox** [comment]
Hi!

This will not be fixed as the domain is not used for anything anyways. I'll remove the link from repo in due time

**Comment by ImMattDavison** [comment]
> Hi!
> 
> This will not be fixed as the domain is not used for anything anyways. I'll remove the link from repo in due time

Sounds good!
